### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by iratekalypso**
(?i) is breaking the CC it seems.

### CODE REVIEW

**Comment by Jo3-L** [comment]
context? `(?i)` is fine here syntactically speaking, don't see any reason why it'd break the CC - need an explanation before I can merge.

**Comment by iratekalypso** [comment]
After troubleshooting in #priority-support on the YAGPDB Discord Server, that was the one thing we needed to change to make the CC work. It seemed to break the REGEX for some reason while testing and setting it up. Once `(?i)` was removed the CC functioned fine.

**Comment by Jo3-L** [comment]
I dunno, `(?i)` should not be breaking in any way there - I suspect you probably just caught Yag during a time of high latency but I'll wait for Satty before closing this.

**Comment by Satty9361** [comment]
[https://regex101.com/r/yWcrlO/1](Regex101 Link)

As you can see the regex is correct. (?i) allows the regex to be case insensitive. 

That must have been definitely some other issue. If you can reproduce any issue, feel free to tag me here/in discord with an invite. 

Will close for now.

**Pull request closed without merging**
