### PR TITLE
feat(moderation): per-user slowmode CC

### PR DESCRIPTION
**Pull request by JordiHakimZiyech**
slowmode per user command
hopefully i've PR'ed it correctly

### CODE REVIEW

**Comment by Jo3-L** [comment]
Hey, thanks for the PR. Some comments though:
1. How is this different from Discord's slowmode / similar implementation in automod(v2)?
2. Please follow the guidelines laid out [here](https://github.com/Jo3-L/yagpdb-cc/blob/master/CONTRIBUTING.md).

**Comment by Satty9361** [comment]
I think this is a per user thing while discord slowmode is for all roles (execpt manage messages etc). In that way it is quite different. Much different implementation as well because this deletes messages while actual slowmode prevents sending them altogether.

**Comment by JordiHakimZiyech** [comment]
yeah it is per user. And yes, it deletes the message. It is possible to prevent them sending messages, but that requires giving a role, and some people just don't like even more roles.

**Comment by Satty9361** [comment]
You need to just format it according to this i guess @JordiHakimZiyech 
Link : https://github.com/Jo3-L/yagpdb-cc/blob/master/CONTRIBUTING.md#leading-comment-syntax

**Comment by Jo3-L** [comment]
In addition to what Satty said, you should put this in a new folder, maybe `moderation` or something. Concept / usage is not suitable for any of the current folders other than `util`, and that's a stretch as well.

Also, looking at the code, 
```lua
{{ $time := 10 }} 
{{ if eq (toInt (dbGet 2 "slowmode").Value) 0 }}
{{ dbSetExpire 2 "slowmode" 1 $time }}
{{ else }}
{{ if eq (toInt (dbGet 2 "slowmode").Value) 1 }} 
{{ deleteTrigger 0 }}
{{ end }}
{{ end }}
```
Does not seem to be user-based (though that could be changed). I'll be leaving this unmerged for now.

**Comment by JordiHakimZiyech** [comment]
yeah. My bad. i'll change it in a bit and i'll drop it in a new file then

**Comment by Jo3-L** [comment]
Closing due to inactivity, please feel free to make a new PR if you wish.

**Pull request closed without merging**
